import { Armchair, FileText, Layers, Monitor, Wifi } from "lucide-react";

const CATEGORIES = [
  { id: "all",       label: "Semua Kategori",          count: 6, Icon: Layers   },
  { id: "elektronik",label: "Elektronik & Gadget",     count: 2, Icon: Monitor  },
  { id: "furnitur",  label: "Furnitur & Meja Kerja",   count: 2, Icon: Armchair },
  { id: "atk",       label: "Alat Tulis Kantor (ATK)", count: 1, Icon: FileText },
  { id: "jaringan",  label: "Perangkat Jaringan",      count: 1, Icon: Wifi     },
];
 
const ITEMS = [
  {
    id: 1,
    name: "Cisco Catalyst Switch 24-Port",
    sku: "SKU-NW-CIS24",
    category: "jaringan",
    categoryLabel: "Perangkat Jaringan",
    price: 12500000,
    stock: 8,
    minStock: 3,
    status: "tersedia",
    image: "https://placehold.co/64x64/e0f2fe/0284c7?text=SW",
  },
  {
    id: 2,
    name: "Kertas Sinar Dunia HVS A4 80g",
    sku: "SKU-OF-HVS80",
    category: "atk",
    categoryLabel: "Alat Tulis Kantor (ATK)",
    price: 55000,
    stock: 120,
    minStock: 20,
    status: "tersedia",
    image: "https://placehold.co/64x64/f0fdf4/16a34a?text=KR",
  },
  {
    id: 3,
    name: "Kursi Kantor Ergonomis Aero-X",
    sku: "SKU-FN-AEROX",
    category: "furnitur",
    categoryLabel: "Furnitur & Meja Kerja",
    price: 3850000,
    stock: 3,
    minStock: 5,
    status: "kritis",
    image: "https://placehold.co/64x64/fff7ed/ea580c?text=KS",
  },
  {
    id: 4,
    name: "Laptop Dell Inspiron 15 3000",
    sku: "SKU-EL-DELL15",
    category: "elektronik",
    categoryLabel: "Elektronik & Gadget",
    price: 8750000,
    stock: 0,
    minStock: 2,
    status: "habis",
    image: "https://placehold.co/64x64/faf5ff/9333ea?text=LP",
  },
  {
    id: 5,
    name: 'Monitor LG 27" IPS 4K',
    sku: "SKU-EL-LG27K",
    category: "elektronik",
    categoryLabel: "Elektronik & Gadget",
    price: 6200000,
    stock: 14,
    minStock: 3,
    status: "tersedia",
    image: "https://placehold.co/64x64/eff6ff/2563eb?text=MN",
  },
  {
    id: 6,
    name: "Meja Kerja Standing Desk Pro",
    sku: "SKU-FN-SDPRO",
    category: "furnitur",
    categoryLabel: "Furnitur & Meja Kerja",
    price: 4500000,
    stock: 7,
    minStock: 2,
    status: "tersedia",
    image: "https://placehold.co/64x64/f0fdf4/15803d?text=MJ",
  },
];

export { CATEGORIES, ITEMS }